from datetime import date

from flask import render_template

quotes = [
  "Be the reason someone smiles today.",
  "You are enough just as you are.",
  "Be the reason someone smiles today.",
  "Kindness is free. Sprinkle it everywhere.",
  "Confidence level: selfie with no filter.",
  "Stay positive. Work hard. Make it happen.",
  "You are stronger than you think.",
  "The only limit is your imagination.",
  "Always be yourself… unless you can be Batman.",
  "Monday is for fresh starts (and more coffee).",
  "You miss 100% of the naps you don’t take.",
  "Do more things that make you forget to check your phone.",
  "Do it with passion or not at all.",
  "Don't grow up, it's a trap!",
  "Laughing burns calories – so keep laughing!",
  "Always be yourself… unless you can be Batman.",
  "Dream big. Nap hard.",
  "You are enough just as you are.",
  "Be yourself; everyone else is already taken.",
  "Be the reason someone smiles today.",
  "Wake up, be awesome, repeat.",
  "Don't grow up, it's a trap!",
  "If you’re going through hell, keep going.",
  "You are stronger than you think.",
  "Every pizza is a personal pizza if you try hard enough.",
  "Success is not final, failure is not fatal.",
  "Stay positive. Work hard. Make it happen.",
  "Keep your heels, head, and standards high.",
  "Be a voice, not an echo.",
  "Don’t be busy, be productive.",
  "Don’t quit your daydream.",
  "The only limit is your imagination.",
  "Coffee first. Schemes later.",
  "You are enough just as you are.",
  "Smile! It confuses people.",
  "Dream big. Nap hard.",
  "Always be yourself… unless you can be Batman.",
  "Life is tough but so are you.",
  "Coffee first. Schemes later.",
  "Don't grow up, it's a trap!",
  "Coffee first. Schemes later.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Don’t quit your daydream.",
  "You glow differently when you're happy.",
  "Don't grow up, it's a trap!",
  "Keep calm and pretend it’s on the lesson plan.",
  "Don’t quit your daydream.",
  "Why fit in when you were born to stand out?",
  "Keep your heels, head, and standards high.",
  "Every pizza is a personal pizza if you try hard enough.",
  "Be a voice, not an echo.",
  "You are enough just as you are.",
  "The best way to predict the future is to create it.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Coffee first. Schemes later.",
  "Always be yourself… unless you can be Batman.",
  "Life is short. Smile while you still have teeth.",
  "Confidence level: selfie with no filter.",
  "Dream big. Nap hard.",
  "Be the reason someone smiles today.",
  "Smile! It confuses people.",
  "When life gives you lemons, make a mojito.",
  "Don’t be busy, be productive.",
  "Monday is for fresh starts (and more coffee).",
  "When life gives you lemons, make a mojito.",
  "Believe you can and you're halfway there.",
  "Dream big. Nap hard.",
  "Don't grow up, it's a trap!",
  "Confidence level: selfie with no filter.",
  "Sarcasm: just one of the many services I offer.",
  "If you’re going through hell, keep going.",
  "Dream big. Nap hard.",
  "Positive mind. Positive vibes. Positive life.",
  "You are stronger than you think.",
  "Positive mind. Positive vibes. Positive life.",
  "Wake up, be awesome, repeat.",
  "If you’re going through hell, keep going.",
  "Every day is a second chance.",
  "Believe you can and you're halfway there.",
  "You are stronger than you think.",
  "You didn’t come this far to only come this far.",
  "Confidence level: selfie with no filter.",
  "Confidence level: selfie with no filter.",
  "Wake up, be awesome, repeat.",
  "Don't grow up, it's a trap!",
  "You're doing great. Keep going!",
  "Success is not final, failure is not fatal.",
  "Life is short. Smile while you still have teeth.",
  "Even Mondays can be good if you believe hard enough.",
  "Be the reason someone smiles today.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Be yourself; everyone else is already taken.",
  "You are enough just as you are.",
  "Believe you can and you're halfway there.",
  "Do more things that make you forget to check your phone.",
  "You're one in a melon!",
  "Confidence level: selfie with no filter.",
  "Life is short. Smile while you still have teeth.",
  "If at first you don’t succeed, redefine success.",
  "Sarcasm: just one of the many services I offer.",
  "Life is tough but so are you.",
  "Make today so awesome that yesterday gets jealous.",
  "You're doing great. Keep going!",
  "You miss 100% of the naps you don’t take.",
  "Dream big. Nap hard.",
  "The only limit is your imagination.",
  "Why fit in when you were born to stand out?",
  "You didn’t come this far to only come this far.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Do it with passion or not at all.",
  "You are capable of amazing things.",
  "The best way to predict the future is to create it.",
  "Eat. Sleep. Conquer. Repeat.",
  "You're doing great. Keep going!",
  "You are enough just as you are.",
  "If you’re going through hell, keep going.",
  "Don’t be busy, be productive.",
  "Smile! It confuses people.",
  "You are capable of amazing things.",
  "Always be yourself… unless you can be Batman.",
  "Life is short. Smile while you still have teeth.",
  "Kindness is free. Sprinkle it everywhere.",
  "Keep your heels, head, and standards high.",
  "You miss 100% of the naps you don’t take.",
  "Believe you can and you're halfway there.",
  "Don’t quit your daydream.",
  "Wake up, be awesome, repeat.",
  "Don't grow up, it's a trap!",
  "You miss 100% of the naps you don’t take.",
  "The best way to predict the future is to create it.",
  "You are capable of amazing things.",
  "If you’re going through hell, keep going.",
  "Make today so awesome that yesterday gets jealous.",
  "Life is tough but so are you.",
  "Be a rainbow in someone else’s cloud.",
  "Don't grow up, it's a trap!",
  "Work hard. Nap harder.",
  "Don’t be busy, be productive.",
  "Think like a proton. Always positive.",
  "Sarcasm: just one of the many services I offer.",
  "The best way to predict the future is to create it.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Sarcasm: just one of the many services I offer.",
  "You're doing great. Keep going!",
  "Wake up, be awesome, repeat.",
  "Be a voice, not an echo.",
  "Do it with passion or not at all.",
  "Make today so awesome that yesterday gets jealous.",
  "If you’re going through hell, keep going.",
  "Work hard. Nap harder.",
  "Every pizza is a personal pizza if you try hard enough.",
  "Be the reason someone smiles today.",
  "Don’t quit your daydream.",
  "Kindness is free. Sprinkle it everywhere.",
  "Always be yourself… unless you can be Batman.",
  "Every day is a second chance.",
  "Monday is for fresh starts (and more coffee).",
  "Be a voice, not an echo.",
  "You are capable of amazing things.",
  "Don't grow up, it's a trap!",
  "Laughing burns calories – so keep laughing!",
  "Sarcasm: just one of the many services I offer.",
  "Don’t quit your daydream.",
  "Coffee first. Schemes later.",
  "Eat. Sleep. Conquer. Repeat.",
  "The only limit is your imagination.",
  "When life gives you lemons, make a mojito.",
  "The only limit is your imagination.",
  "Even Mondays can be good if you believe hard enough.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Coffee first. Schemes later.",
  "If you’re going through hell, keep going.",
  "Smile! It confuses people.",
  "Strive for progress, not perfection.",
  "When life gives you lemons, make a mojito.",
  "Make today so awesome that yesterday gets jealous.",
  "Kindness is free. Sprinkle it everywhere.",
  "Every day is a second chance.",
  "When life gives you lemons, make a mojito.",
  "Work hard. Nap harder.",
  "Stay positive. Work hard. Make it happen.",
  "The best way to predict the future is to create it.",
  "Always be yourself… unless you can be Batman.",
  "Every day is a second chance.",
  "Be the reason someone smiles today.",
  "You're doing great. Keep going!",
  "Life is tough but so are you.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Every day is a second chance.",
  "If at first you don’t succeed, redefine success.",
  "You didn’t come this far to only come this far.",
  "Be a rainbow in someone else’s cloud.",
  "You're doing great. Keep going!",
  "Be yourself; everyone else is already taken.",
  "Every pizza is a personal pizza if you try hard enough.",
  "You're doing great. Keep going!",
  "Be yourself; everyone else is already taken.",
  "You miss 100% of the naps you don’t take.",
  "Laughing burns calories – so keep laughing!",
  "Strive for progress, not perfection.",
  "Think like a proton. Always positive.",
  "Coffee first. Schemes later.",
  "You glow differently when you're happy.",
  "Be the reason someone smiles today.",
  "Don't grow up, it's a trap!",
  "Always be yourself… unless you can be Batman.",
  "Believe you can and you're halfway there.",
  "Wake up, be awesome, repeat.",
  "Why fit in when you were born to stand out?",
  "Success is not final, failure is not fatal.",
  "Dream big. Nap hard.",
  "Smile! It confuses people.",
  "Success is not final, failure is not fatal.",
  "Don't grow up, it's a trap!",
  "Think like a proton. Always positive.",
  "Do more things that make you forget to check your phone.",
  "Laughing burns calories – so keep laughing!",
  "Be yourself; everyone else is already taken.",
  "Do it with passion or not at all.",
  "Do more things that make you forget to check your phone.",
  "Always be yourself… unless you can be Batman.",
  "You are enough just as you are.",
  "You are enough just as you are.",
  "You miss 100% of the naps you don’t take.",
  "Be a rainbow in someone else’s cloud.",
  "You are capable of amazing things.",
  "The best way to predict the future is to create it.",
  "Sarcasm: just one of the many services I offer.",
  "Every pizza is a personal pizza if you try hard enough.",
  "The only limit is your imagination.",
  "Don’t be busy, be productive.",
  "When nothing goes right, go left.",
  "Keep your heels, head, and standards high.",
  "You are enough just as you are.",
  "Don’t quit your daydream.",
  "You are capable of amazing things.",
  "Be the reason someone smiles today.",
  "Life is tough but so are you.",
  "When nothing goes right, go left.",
  "If you’re going through hell, keep going.",
  "You're doing great. Keep going!",
  "Be yourself; everyone else is already taken.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Think like a proton. Always positive.",
  "Don’t quit your daydream.",
  "Do it with passion or not at all.",
  "You're one in a melon!",
  "If at first you don’t succeed, redefine success.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Stay positive. Work hard. Make it happen.",
  "Smile! It confuses people.",
  "Every pizza is a personal pizza if you try hard enough.",
  "Every pizza is a personal pizza if you try hard enough.",
  "Laughing burns calories – so keep laughing!",
  "Wake up, be awesome, repeat.",
  "If you’re going through hell, keep going.",
  "Make today so awesome that yesterday gets jealous.",
  "When life gives you lemons, make a mojito.",
  "Believe you can and you're halfway there.",
  "Keep calm and pretend it’s on the lesson plan.",
  "The best way to predict the future is to create it.",
  "Success is not final, failure is not fatal.",
  "You are stronger than you think.",
  "When nothing goes right, go left.",
  "Wake up, be awesome, repeat.",
  "Life is tough but so are you.",
  "The only limit is your imagination.",
  "You are capable of amazing things.",
  "You are enough just as you are.",
  "Smile! It confuses people.",
  "Make today so awesome that yesterday gets jealous.",
  "The only limit is your imagination.",
  "Positive mind. Positive vibes. Positive life.",
  "Every day is a second chance.",
  "Eat. Sleep. Conquer. Repeat.",
  "Even Mondays can be good if you believe hard enough.",
  "Always be yourself… unless you can be Batman.",
  "Eat. Sleep. Conquer. Repeat.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Work hard. Nap harder.",
  "Be a rainbow in someone else’s cloud.",
  "Don't grow up, it's a trap!",
  "Don't grow up, it's a trap!",
  "Life is tough but so are you.",
  "Don’t quit your daydream.",
  "Kindness is free. Sprinkle it everywhere.",
  "Every day is a second chance.",
  "You're one in a melon!",
  "Do it with passion or not at all.",
  "Confidence level: selfie with no filter.",
  "Life is short. Smile while you still have teeth.",
  "Even Mondays can be good if you believe hard enough.",
  "Always be yourself… unless you can be Batman.",
  "Work hard. Nap harder.",
  "Don’t be busy, be productive.",
  "Even Mondays can be good if you believe hard enough.",
  "Eat. Sleep. Conquer. Repeat.",
  "You didn’t come this far to only come this far.",
  "You glow differently when you're happy.",
  "Wake up, be awesome, repeat.",
  "Don’t quit your daydream.",
  "You are enough just as you are.",
  "Be the reason someone smiles today.",
  "Every pizza is a personal pizza if you try hard enough.",
  "If at first you don’t succeed, redefine success.",
  "Don't grow up, it's a trap!",
  "Think like a proton. Always positive.",
  "Keep your heels, head, and standards high.",
  "Be the reason someone smiles today.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Dream big. Nap hard.",
  "Confidence level: selfie with no filter.",
  "If at first you don’t succeed, redefine success.",
  "Keep calm and pretend it’s on the lesson plan.",
  "If you’re going through hell, keep going.",
  "The best way to predict the future is to create it.",
  "Coffee first. Schemes later.",
  "Wake up, be awesome, repeat.",
  "You are capable of amazing things.",
  "Stay positive. Work hard. Make it happen.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Keep your heels, head, and standards high.",
  "Laughing burns calories – so keep laughing!",
  "When nothing goes right, go left.",
  "Kindness is free. Sprinkle it everywhere.",
  "Work hard. Nap harder.",
  "Kindness is free. Sprinkle it everywhere.",
  "Always be yourself… unless you can be Batman.",
  "When life gives you lemons, make a mojito.",
  "Don't grow up, it's a trap!",
  "You miss 100% of the naps you don’t take.",
  "You are capable of amazing things.",
  "You glow differently when you're happy.",
  "The best way to predict the future is to create it.",
  "Don’t quit your daydream.",
  "Don't grow up, it's a trap!",
  "Believe you can and you're halfway there.",
  "Wake up, be awesome, repeat.",
  "Monday is for fresh starts (and more coffee).",
  "Life is short. Smile while you still have teeth.",
  "If at first you don’t succeed, redefine success.",
  "Be a rainbow in someone else’s cloud.",
  "You glow differently when you're happy.",
  "Work hard. Nap harder.",
  "Every pizza is a personal pizza if you try hard enough.",
  "Work hard. Nap harder.",
  "Work hard. Nap harder.",
  "Do it with passion or not at all.",
  "Coffee first. Schemes later.",
  "Do more things that make you forget to check your phone.",
  "Do more things that make you forget to check your phone.",
  "You are stronger than you think.",
  "Make today so awesome that yesterday gets jealous.",
  "Strive for progress, not perfection.",
  "Laughing burns calories – so keep laughing!",
  "Strive for progress, not perfection.",
  "Wake up, be awesome, repeat.",
  "Coffee first. Schemes later.",
  "Be a rainbow in someone else’s cloud.",
  "Do it with passion or not at all.",
  "Don't grow up, it's a trap!",
  "Don’t be busy, be productive.",
  "Be the reason someone smiles today.",
  "Stay positive. Work hard. Make it happen.",
  "Make today so awesome that yesterday gets jealous.",
  "Strive for progress, not perfection.",
  "Wake up, be awesome, repeat.",
  "Success is not final, failure is not fatal.",
  "If at first you don’t succeed, redefine success.",
  "Some people graduate with honors, I am just honored to graduate.",
  "When life gives you lemons, make a mojito.",
  "Dream big. Nap hard.",
  "Strive for progress, not perfection.",
  "You miss 100% of the naps you don’t take.",
  "Believe you can and you're halfway there.",
  "Always be yourself… unless you can be Batman.",
  "Do more things that make you forget to check your phone.",
  "If at first you don’t succeed, redefine success.",
  "Smile! It confuses people.",
  "Stay positive. Work hard. Make it happen.",
  "Keep calm and pretend it’s on the lesson plan.",
  "When nothing goes right, go left.",
  "You didn’t come this far to only come this far.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Dream big. Nap hard.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Be a rainbow in someone else’s cloud.",
  "You are stronger than you think.",
  "Be a rainbow in someone else’s cloud.",
  "Stay positive. Work hard. Make it happen.",
  "Kindness is free. Sprinkle it everywhere.",
  "Think like a proton. Always positive.",
  "Don't grow up, it's a trap!",
  "Life is short. Smile while you still have teeth.",
  "Strive for progress, not perfection.",
  "Monday is for fresh starts (and more coffee).",
  "Do more things that make you forget to check your phone.",
  "If at first you don’t succeed, redefine success.",
  "Work hard. Nap harder.",
  "If you’re going through hell, keep going.",
  "Be yourself; everyone else is already taken.",
  "If you’re going through hell, keep going.",
  "You are capable of amazing things.",
  "Believe you can and you're halfway there.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Don't grow up, it's a trap!",
  "Success is not final, failure is not fatal.",
  "Be the reason someone smiles today.",
  "Dream big. Nap hard.",
  "Strive for progress, not perfection.",
  "Be a voice, not an echo.",
  "Every pizza is a personal pizza if you try hard enough.",
  "You're doing great. Keep going!",
  "You didn’t come this far to only come this far.",
  "Believe you can and you're halfway there.",
  "The only limit is your imagination.",
  "Strive for progress, not perfection.",
  "If you’re going through hell, keep going.",
  "Dream big. Nap hard.",
  "Always be yourself… unless you can be Batman.",
  "Mistakes are proof that you are trying.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Always be yourself… unless you can be Batman.",
  "Positive mind. Positive vibes. Positive life.",
  "Work hard. Nap harder.",
  "Every pizza is a personal pizza if you try hard enough.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Be a rainbow in someone else’s cloud.",
  "Think like a proton. Always positive.",
  "You miss 100% of the naps you don’t take.",
  "Life is short. Smile while you still have teeth.",
  "Dream big. Nap hard.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Confidence level: selfie with no filter.",
  "Life is tough but so are you.",
  "Always be yourself… unless you can be Batman.",
  "Work hard. Nap harder.",
  "Coffee first. Schemes later.",
  "You are enough just as you are.",
  "The best way to predict the future is to create it.",
  "Kindness is free. Sprinkle it everywhere.",
  "You glow differently when you're happy.",
  "Believe you can and you're halfway there.",
  "Monday is for fresh starts (and more coffee).",
  "You glow differently when you're happy.",
  "Be the reason someone smiles today.",
  "Positive mind. Positive vibes. Positive life.",
  "Keep your heels, head, and standards high.",
  "Kindness is free. Sprinkle it everywhere.",
  "Even Mondays can be good if you believe hard enough.",
  "You miss 100% of the naps you don’t take.",
  "You glow differently when you're happy.",
  "You are stronger than you think.",
  "Positive mind. Positive vibes. Positive life.",
  "Do more things that make you forget to check your phone.",
  "Monday is for fresh starts (and more coffee).",
  "Every pizza is a personal pizza if you try hard enough.",
  "You're one in a melon!",
  "Dream big. Nap hard.",
  "Strive for progress, not perfection.",
  "Be the reason someone smiles today.",
  "Positive mind. Positive vibes. Positive life.",
  "Smile! It confuses people.",
  "Eat. Sleep. Conquer. Repeat.",
  "Don’t be busy, be productive.",
  "Don’t quit your daydream.",
  "Work hard. Nap harder.",
  "Do more things that make you forget to check your phone.",
  "Do it with passion or not at all.",
  "Monday is for fresh starts (and more coffee).",
  "Life is tough but so are you.",
  "Be a rainbow in someone else’s cloud.",
  "Don’t be busy, be productive.",
  "You are stronger than you think.",
  "Keep your heels, head, and standards high.",
  "You're doing great. Keep going!",
  "Strive for progress, not perfection.",
  "Don’t quit your daydream.",
  "You didn’t come this far to only come this far.",
  "Why fit in when you were born to stand out?",
  "Kindness is free. Sprinkle it everywhere.",
  "Always be yourself… unless you can be Batman.",
  "Do more things that make you forget to check your phone.",
  "Be a rainbow in someone else’s cloud.",
  "Some people graduate with honors, I am just honored to graduate.",
  "You're one in a melon!",
  "Eat. Sleep. Conquer. Repeat.",
  "Don’t quit your daydream.",
  "Make today so awesome that yesterday gets jealous.",
  "You're doing great. Keep going!",
  "Eat. Sleep. Conquer. Repeat.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Why fit in when you were born to stand out?",
  "You are enough just as you are.",
  "Don’t quit your daydream.",
  "Be yourself; everyone else is already taken.",
  "Wake up, be awesome, repeat.",
  "The best way to predict the future is to create it.",
  "Wake up, be awesome, repeat.",
  "Wake up, be awesome, repeat.",
  "Do more things that make you forget to check your phone.",
  "Strive for progress, not perfection.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Success is not final, failure is not fatal.",
  "Be yourself; everyone else is already taken.",
  "Do it with passion or not at all.",
  "If you’re going through hell, keep going.",
  "Think like a proton. Always positive.",
  "Be a rainbow in someone else’s cloud.",
  "Coffee first. Schemes later.",
  "Don’t quit your daydream.",
  "Don’t quit your daydream.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Coffee first. Schemes later.",
  "Be a voice, not an echo.",
  "You glow differently when you're happy.",
  "You are enough just as you are.",
  "You didn’t come this far to only come this far.",
  "When nothing goes right, go left.",
  "You're one in a melon!",
  "Don’t be busy, be productive.",
  "Don’t be busy, be productive.",
  "Laughing burns calories – so keep laughing!",
  "Think like a proton. Always positive.",
  "The only limit is your imagination.",
  "The best way to predict the future is to create it.",
  "The only limit is your imagination.",
  "Monday is for fresh starts (and more coffee).",
  "The best way to predict the future is to create it.",
  "You didn’t come this far to only come this far.",
  "Sarcasm: just one of the many services I offer.",
  "Don't grow up, it's a trap!",
  "Kindness is free. Sprinkle it everywhere.",
  "You are enough just as you are.",
  "Don’t quit your daydream.",
  "You are stronger than you think.",
  "Kindness is free. Sprinkle it everywhere.",
  "You're doing great. Keep going!",
  "You are enough just as you are.",
  "Think like a proton. Always positive.",
  "Keep your heels, head, and standards high.",
  "You're doing great. Keep going!",
  "You are stronger than you think.",
  "Confidence level: selfie with no filter.",
  "Don’t be busy, be productive.",
  "Life is tough but so are you.",
  "Sarcasm: just one of the many services I offer.",
  "When nothing goes right, go left.",
  "Do it with passion or not at all.",
  "Keep calm and pretend it’s on the lesson plan.",
  "The best way to predict the future is to create it.",
  "Confidence level: selfie with no filter.",
  "Coffee first. Schemes later.",
  "You're doing great. Keep going!",
  "You're doing great. Keep going!",
  "Life is short. Smile while you still have teeth.",
  "Believe you can and you're halfway there.",
  "You glow differently when you're happy.",
  "Success is not final, failure is not fatal.",
  "Eat. Sleep. Conquer. Repeat.",
  "Confidence level: selfie with no filter.",
  "Every day is a second chance.",
  "Be the reason someone smiles today.",
  "Mistakes are proof that you are trying.",
  "Do it with passion or not at all.",
  "Don’t be busy, be productive.",
  "Be yourself; everyone else is already taken.",
  "You are capable of amazing things.",
  "When life gives you lemons, make a mojito.",
  "Positive mind. Positive vibes. Positive life.",
  "Don't grow up, it's a trap!",
  "Strive for progress, not perfection.",
  "Strive for progress, not perfection.",
  "Smile! It confuses people.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Every day is a second chance.",
  "Do more things that make you forget to check your phone.",
  "Always be yourself… unless you can be Batman.",
  "Why fit in when you were born to stand out?",
  "You are enough just as you are.",
  "Always be yourself… unless you can be Batman.",
  "Smile! It confuses people.",
  "You are enough just as you are.",
  "Why fit in when you were born to stand out?",
  "Be yourself; everyone else is already taken.",
  "You are stronger than you think.",
  "You are capable of amazing things.",
  "Work hard. Nap harder.",
  "Success is not final, failure is not fatal.",
  "Keep your heels, head, and standards high.",
  "Don’t be busy, be productive.",
  "Laughing burns calories – so keep laughing!",
  "Coffee first. Schemes later.",
  "Kindness is free. Sprinkle it everywhere.",
  "If you’re going through hell, keep going.",
  "Smile! It confuses people.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Monday is for fresh starts (and more coffee).",
  "Life is short. Smile while you still have teeth.",
  "Be a voice, not an echo.",
  "Don’t be busy, be productive.",
  "Stay positive. Work hard. Make it happen.",
  "Kindness is free. Sprinkle it everywhere.",
  "You are capable of amazing things.",
  "Always be yourself… unless you can be Batman.",
  "If you’re going through hell, keep going.",
  "Think like a proton. Always positive.",
  "You miss 100% of the naps you don’t take.",
  "Kindness is free. Sprinkle it everywhere.",
  "You glow differently when you're happy.",
  "Even Mondays can be good if you believe hard enough.",
  "Confidence level: selfie with no filter.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Every day is a second chance.",
  "Be yourself; everyone else is already taken.",
  "You are capable of amazing things.",
  "You glow differently when you're happy.",
  "You're doing great. Keep going!",
  "Life is short. Smile while you still have teeth.",
  "Be a rainbow in someone else’s cloud.",
  "Life is tough but so are you.",
  "When life gives you lemons, make a mojito.",
  "Sarcasm: just one of the many services I offer.",
  "Don’t quit your daydream.",
  "You are stronger than you think.",
  "Some people graduate with honors, I am just honored to graduate.",
  "You're doing great. Keep going!",
  "If you’re going through hell, keep going.",
  "Sarcasm: just one of the many services I offer.",
  "Success is not final, failure is not fatal.",
  "Don't grow up, it's a trap!",
  "You're doing great. Keep going!",
  "Stay positive. Work hard. Make it happen.",
  "Sarcasm: just one of the many services I offer.",
  "Do it with passion or not at all.",
  "Strive for progress, not perfection.",
  "Positive mind. Positive vibes. Positive life.",
  "Smile! It confuses people.",
  "Life is short. Smile while you still have teeth.",
  "You are capable of amazing things.",
  "You miss 100% of the naps you don’t take.",
  "Keep your heels, head, and standards high.",
  "Dream big. Nap hard.",
  "Always be yourself… unless you can be Batman.",
  "Stay positive. Work hard. Make it happen.",
  "If at first you don’t succeed, redefine success.",
  "You didn’t come this far to only come this far.",
  "When nothing goes right, go left.",
  "When life gives you lemons, make a mojito.",
  "Do it with passion or not at all.",
  "Do more things that make you forget to check your phone.",
  "Smile! It confuses people.",
  "Always be yourself… unless you can be Batman.",
  "Don’t quit your daydream.",
  "Dream big. Nap hard.",
  "When nothing goes right, go left.",
  "Mistakes are proof that you are trying.",
  "Every day is a second chance.",
  "Sarcasm: just one of the many services I offer.",
  "You miss 100% of the naps you don’t take.",
  "Even Mondays can be good if you believe hard enough.",
  "When nothing goes right, go left.",
  "Coffee first. Schemes later.",
  "Do more things that make you forget to check your phone.",
  "Don't grow up, it's a trap!",
  "Laughing burns calories – so keep laughing!",
  "Strive for progress, not perfection.",
  "Think like a proton. Always positive.",
  "When life gives you lemons, make a mojito.",
  "If you’re going through hell, keep going.",
  "You miss 100% of the naps you don’t take.",
  "Life is tough but so are you.",
  "You're one in a melon!",
  "Keep calm and pretend it’s on the lesson plan.",
  "Keep calm and pretend it’s on the lesson plan.",
  "You're doing great. Keep going!",
  "You're one in a melon!",
  "Be the reason someone smiles today.",
  "Eat. Sleep. Conquer. Repeat.",
  "When nothing goes right, go left.",
  "Keep your heels, head, and standards high.",
  "Coffee first. Schemes later.",
  "Even Mondays can be good if you believe hard enough.",
  "Always be yourself… unless you can be Batman.",
  "When nothing goes right, go left.",
  "You miss 100% of the naps you don’t take.",
  "You are enough just as you are.",
  "Confidence level: selfie with no filter.",
  "You glow differently when you're happy.",
  "Kindness is free. Sprinkle it everywhere.",
  "Monday is for fresh starts (and more coffee).",
  "Stay positive. Work hard. Make it happen.",
  "Every day is a second chance.",
  "Always be yourself… unless you can be Batman.",
  "Be a rainbow in someone else’s cloud.",
  "Work hard. Nap harder.",
  "Keep your heels, head, and standards high.",
  "Confidence level: selfie with no filter.",
  "Positive mind. Positive vibes. Positive life.",
  "Stay positive. Work hard. Make it happen.",
  "Smile! It confuses people.",
  "Coffee first. Schemes later.",
  "Do more things that make you forget to check your phone.",
  "You miss 100% of the naps you don’t take.",
  "When life gives you lemons, make a mojito.",
  "Make today so awesome that yesterday gets jealous.",
  "Keep your heels, head, and standards high.",
  "If you’re going through hell, keep going.",
  "Why fit in when you were born to stand out?",
  "Don’t quit your daydream.",
  "Think like a proton. Always positive.",
  "Life is short. Smile while you still have teeth.",
  "Life is short. Smile while you still have teeth.",
  "Laughing burns calories – so keep laughing!",
  "The only limit is your imagination.",
  "Be yourself; everyone else is already taken.",
  "Mistakes are proof that you are trying.",
  "You are capable of amazing things.",
  "Do it with passion or not at all.",
  "You're one in a melon!",
  "Kindness is free. Sprinkle it everywhere.",
  "Believe you can and you're halfway there.",
  "Positive mind. Positive vibes. Positive life.",
  "You are enough just as you are.",
  "The only limit is your imagination.",
  "The only limit is your imagination.",
  "You glow differently when you're happy.",
  "Why fit in when you were born to stand out?",
  "Don't grow up, it's a trap!",
  "You are enough just as you are.",
  "Be yourself; everyone else is already taken.",
  "If at first you don’t succeed, redefine success.",
  "Make today so awesome that yesterday gets jealous.",
  "Dream big. Nap hard.",
  "You didn’t come this far to only come this far.",
  "Confidence level: selfie with no filter.",
  "Strive for progress, not perfection.",
  "You're one in a melon!",
  "Always be yourself… unless you can be Batman.",
  "Don't grow up, it's a trap!",
  "Do more things that make you forget to check your phone.",
  "Be a voice, not an echo.",
  "Be a rainbow in someone else’s cloud.",
  "You miss 100% of the naps you don’t take.",
  "Laughing burns calories – so keep laughing!",
  "Do it with passion or not at all.",
  "The only limit is your imagination.",
  "You are capable of amazing things.",
  "If at first you don’t succeed, redefine success.",
  "When nothing goes right, go left.",
  "Smile! It confuses people.",
  "You're one in a melon!",
  "Eat. Sleep. Conquer. Repeat.",
  "Success is not final, failure is not fatal.",
  "Do it with passion or not at all.",
  "Coffee first. Schemes later.",
  "Do more things that make you forget to check your phone.",
  "You didn’t come this far to only come this far.",
  "Coffee first. Schemes later.",
  "The best way to predict the future is to create it.",
  "Laughing burns calories – so keep laughing!",
  "Sarcasm: just one of the many services I offer.",
  "When life gives you lemons, make a mojito.",
  "Believe you can and you're halfway there.",
  "Think like a proton. Always positive.",
  "You didn’t come this far to only come this far.",
  "When nothing goes right, go left.",
  "Be a rainbow in someone else’s cloud.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Do more things that make you forget to check your phone.",
  "Think like a proton. Always positive.",
  "Smile! It confuses people.",
  "Dream big. Nap hard.",
  "Every pizza is a personal pizza if you try hard enough.",
  "The best way to predict the future is to create it.",
  "Strive for progress, not perfection.",
  "If at first you don’t succeed, redefine success.",
  "If at first you don’t succeed, redefine success.",
  "Smile! It confuses people.",
  "Kindness is free. Sprinkle it everywhere.",
  "Success is not final, failure is not fatal.",
  "Do more things that make you forget to check your phone.",
  "Wake up, be awesome, repeat.",
  "When life gives you lemons, make a mojito.",
  "If at first you don’t succeed, redefine success.",
  "Laughing burns calories – so keep laughing!",
  "Be a voice, not an echo.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Don’t be busy, be productive.",
  "Kindness is free. Sprinkle it everywhere.",
  "Do more things that make you forget to check your phone.",
  "Sarcasm: just one of the many services I offer.",
  "The best way to predict the future is to create it.",
  "You're one in a melon!",
  "Strive for progress, not perfection.",
  "Laughing burns calories – so keep laughing!",
  "Every day is a second chance.",
  "Confidence level: selfie with no filter.",
  "Be a rainbow in someone else’s cloud.",
  "Coffee first. Schemes later.",
  "Mistakes are proof that you are trying.",
  "Success is not final, failure is not fatal.",
  "Every day is a second chance.",
  "Success is not final, failure is not fatal.",
  "Sarcasm: just one of the many services I offer.",
  "Smile! It confuses people.",
  "Be a rainbow in someone else’s cloud.",
  "You are enough just as you are.",
  "Be the reason someone smiles today.",
  "Mistakes are proof that you are trying.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Positive mind. Positive vibes. Positive life.",
  "Every day is a second chance.",
  "You are capable of amazing things.",
  "Mistakes are proof that you are trying.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Life is tough but so are you.",
  "Always be yourself… unless you can be Batman.",
  "Be yourself; everyone else is already taken.",
  "Do it with passion or not at all.",
  "Don’t quit your daydream.",
  "Strive for progress, not perfection.",
  "Every pizza is a personal pizza if you try hard enough.",
  "Dream big. Nap hard.",
  "Even Mondays can be good if you believe hard enough.",
  "If you’re going through hell, keep going.",
  "Think like a proton. Always positive.",
  "You are enough just as you are.",
  "You didn’t come this far to only come this far.",
  "Do more things that make you forget to check your phone.",
  "Kindness is free. Sprinkle it everywhere.",
  "Do it with passion or not at all.",
  "Don’t quit your daydream.",
  "You are stronger than you think.",
  "You are enough just as you are.",
  "Be a rainbow in someone else’s cloud.",
  "You're one in a melon!",
  "The best way to predict the future is to create it.",
  "Mistakes are proof that you are trying.",
  "Dream big. Nap hard.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Believe you can and you're halfway there.",
  "You're doing great. Keep going!",
  "Eat. Sleep. Conquer. Repeat.",
  "The only limit is your imagination.",
  "Sarcasm: just one of the many services I offer.",
  "Life is tough but so are you.",
  "You're doing great. Keep going!",
  "Laughing burns calories – so keep laughing!",
  "Do it with passion or not at all.",
  "Be a rainbow in someone else’s cloud.",
  "Work hard. Nap harder.",
  "Work hard. Nap harder.",
  "Keep your heels, head, and standards high.",
  "The only limit is your imagination.",
  "Be yourself; everyone else is already taken.",
  "Dream big. Nap hard.",
  "Stay positive. Work hard. Make it happen.",
  "If you’re going through hell, keep going.",
  "Why fit in when you were born to stand out?",
  "Don't grow up, it's a trap!",
  "Smile! It confuses people.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Monday is for fresh starts (and more coffee).",
  "Some people graduate with honors, I am just honored to graduate.",
  "You are enough just as you are.",
  "Smile! It confuses people.",
  "Success is not final, failure is not fatal.",
  "Every day is a second chance.",
  "Wake up, be awesome, repeat.",
  "If you’re going through hell, keep going.",
  "You're doing great. Keep going!",
  "Don’t quit your daydream.",
  "You miss 100% of the naps you don’t take.",
  "You are enough just as you are.",
  "Positive mind. Positive vibes. Positive life.",
  "The only limit is your imagination.",
  "You are stronger than you think.",
  "Think like a proton. Always positive.",
  "Don't grow up, it's a trap!",
  "Kindness is free. Sprinkle it everywhere.",
  "Positive mind. Positive vibes. Positive life.",
  "Strive for progress, not perfection.",
  "Life is short. Smile while you still have teeth.",
  "Every day is a second chance.",
  "Think like a proton. Always positive.",
  "Keep your heels, head, and standards high.",
  "Stay positive. Work hard. Make it happen.",
  "Believe you can and you're halfway there.",
  "Eat. Sleep. Conquer. Repeat.",
  "Sarcasm: just one of the many services I offer.",
  "Be a rainbow in someone else’s cloud.",
  "Eat. Sleep. Conquer. Repeat.",
  "Coffee first. Schemes later.",
  "Be yourself; everyone else is already taken.",
  "When life gives you lemons, make a mojito.",
  "Why fit in when you were born to stand out?",
  "You glow differently when you're happy.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Why fit in when you were born to stand out?",
  "If at first you don’t succeed, redefine success.",
  "When life gives you lemons, make a mojito.",
  "Be a rainbow in someone else’s cloud.",
  "You are capable of amazing things.",
  "Confidence level: selfie with no filter.",
  "Eat. Sleep. Conquer. Repeat.",
  "Life is short. Smile while you still have teeth.",
  "Success is not final, failure is not fatal.",
  "Keep your heels, head, and standards high.",
  "You are stronger than you think.",
  "Do more things that make you forget to check your phone.",
  "Strive for progress, not perfection.",
  "Make today so awesome that yesterday gets jealous.",
  "When nothing goes right, go left.",
  "The only limit is your imagination.",
  "Life is short. Smile while you still have teeth.",
  "You're doing great. Keep going!",
  "Stay positive. Work hard. Make it happen.",
  "Stay positive. Work hard. Make it happen.",
  "When nothing goes right, go left.",
  "The only limit is your imagination.",
  "Some people graduate with honors, I am just honored to graduate.",
  "You're one in a melon!",
  "Confidence level: selfie with no filter.",
  "Kindness is free. Sprinkle it everywhere.",
  "Eat. Sleep. Conquer. Repeat.",
  "Dream big. Nap hard.",
  "If at first you don’t succeed, redefine success.",
  "The only limit is your imagination.",
  "Be yourself; everyone else is already taken.",
  "Sarcasm: just one of the many services I offer.",
  "Monday is for fresh starts (and more coffee).",
  "You are stronger than you think.",
  "You are capable of amazing things.",
  "Do it with passion or not at all.",
  "Kindness is free. Sprinkle it everywhere.",
  "Positive mind. Positive vibes. Positive life.",
  "Monday is for fresh starts (and more coffee).",
  "Do it with passion or not at all.",
  "You are stronger than you think.",
  "Think like a proton. Always positive.",
  "If at first you don’t succeed, redefine success.",
  "Think like a proton. Always positive.",
  "The only limit is your imagination.",
  "You didn’t come this far to only come this far.",
  "Believe you can and you're halfway there.",
  "Confidence level: selfie with no filter.",
  "Eat. Sleep. Conquer. Repeat.",
  "Do it with passion or not at all.",
  "Even Mondays can be good if you believe hard enough.",
  "Always be yourself… unless you can be Batman.",
  "Make today so awesome that yesterday gets jealous.",
  "Keep your heels, head, and standards high.",
  "Laughing burns calories – so keep laughing!",
  "If you’re going through hell, keep going.",
  "Coffee first. Schemes later.",
  "When nothing goes right, go left.",
  "Sarcasm: just one of the many services I offer.",
  "Every pizza is a personal pizza if you try hard enough.",
  "Life is tough but so are you.",
  "You're doing great. Keep going!",
  "You are enough just as you are.",
  "Always be yourself… unless you can be Batman.",
  "Kindness is free. Sprinkle it everywhere.",
  "Mistakes are proof that you are trying.",
  "Kindness is free. Sprinkle it everywhere.",
  "Be yourself; everyone else is already taken.",
  "Smile! It confuses people.",
  "Make today so awesome that yesterday gets jealous.",
  "Wake up, be awesome, repeat.",
  "You are enough just as you are.",
  "Keep calm and pretend it’s on the lesson plan.",
  "Life is short. Smile while you still have teeth.",
  "Be the reason someone smiles today.",
  "Sarcasm: just one of the many services I offer.",
  "Life is tough but so are you.",
  "Why fit in when you were born to stand out?",
  "If you’re going through hell, keep going.",
  "Wake up, be awesome, repeat.",
  "Success is not final, failure is not fatal.",
  "You didn’t come this far to only come this far.",
  "You are capable of amazing things.",
  "Dream big. Nap hard.",
  "Eat. Sleep. Conquer. Repeat.",
  "Believe you can and you're halfway there.",
  "Keep your heels, head, and standards high.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Don’t be busy, be productive.",
  "You miss 100% of the naps you don’t take.",
  "Stay positive. Work hard. Make it happen.",
  "Life is tough but so are you.",
  "If you’re going through hell, keep going.",
  "Be yourself; everyone else is already taken.",
  "Confidence level: selfie with no filter.",
  "Even Mondays can be good if you believe hard enough.",
  "Be the reason someone smiles today.",
  "Confidence level: selfie with no filter.",
  "Make today so awesome that yesterday gets jealous.",
  "Positive mind. Positive vibes. Positive life."
]

def render():
    target_date = date(2025, 7, 25)

    today = date.today()

    days_passed = (today - target_date).days

    index = days_passed % len(quotes)

    return render_template("homeTemplate.html",
                           TEXT=quotes[index],
                           )